<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gridLabelTable</name>
   <tag></tag>
   <elementGuidId>b3042d2d-e25b-4cf6-a376-af5af78ef4c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#labels_table</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;labels_table&quot;)[count(. | //*[@id = 'labels_table']) = count(//*[@id = 'labels_table'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='labels_table']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>labels_table</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table table-striped table-bordered dataTable no-footer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>grid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>labels_table_info</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SWIMS OrderSWIMS DBNameBatchStatusSubmittedCompletedOutgoingReturnview cancel41720Exhartks3623completed08-27 15:52:2908-27 15:52:36794658462655 zpl pngview cancel41719Exhartks3623completed08-27 15:52:2908-27 15:52:36794658462596 zpl pngview cancel41718Exhartks3623completed08-27 15:52:2908-27 15:52:36794658462644 zpl pngview cancel41717Exhartks3623completed08-27 15:52:2908-27 15:52:36794658462633 zpl pngview cancel41716Exhartks3623completed08-27 15:52:2908-27 15:52:35794658462585 zpl pngview cancel41713Exhartks3623completed08-27 15:52:2908-27 15:52:35794658462622 zpl pngview cancel41712Exhartks3623completed08-27 15:52:2908-27 15:52:34794658462574 zpl pngview cancel41711Exhartks3623completed08-27 15:52:2908-27 15:52:34794658462563 zpl pngview cancel41710Exhartks3623completed08-27 15:52:2908-27 15:52:34794658462611 zpl pngview cancel41701Exhartks3623completed08-27 15:52:2908-27 15:52:33794658462552 zpl png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;labels_table&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//table[@id='labels_table']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='labels_table_wrapper']/table</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/following::table[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table</value>
   </webElementXpaths>
</WebElementEntity>
