<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddlWarehouseAddTracking</name>
   <tag></tag>
   <elementGuidId>78a02d27-a6a0-4f89-8b5f-c165e3c5dbeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add_tracking_credential</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='add_tracking_credential']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_tracking_credential</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>wh23_fedexwh7_fedexwh23_upswh7_upswh21_fedexwh34_fedexwh34_upswh27_fedexwh27_upswh33_fedexwh38_fedexwh40_fedexwh33_upswh_38_upswh40_upswh34_westfieldcostco_upswh8_upswh8_fijiwaterfl_upswh8_fedexwh35_fedexwh35_upswh21_endiciawh33_ofmks_upswh33_ofmks_fedexwh38_upswh38_ofmca38_upswh38_ofmca38_fedexwh40_ofmpa40_upswh40_ofmpa40_fedexwh7_endiciawh7_dhlwh37_endiciawh25_upswh25_fedexwh31_upswh31_fedexwh31_endiciawh37_dhlwh41_fedexwh41_upswh37_fedexwh37_upswh26_fedexwh26_upswh34_saferacksnv_fedexwh45_upswh21_upswh42_trafilea_dhlwh18_hmdmo_dhlwh45_fedexwh45_dhlwh42_fedexwh21_uspswh21_usps_Internationalwh18_goodchopmo_fedexwh18_upswh18_goodchopmo_upswh24_fedexwh24_ups</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_tracking_credential&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='add_tracking_credential']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swal2-content']/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'add_tracking_credential', '&quot;', ')')])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
